#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
 for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
 done
 unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
compton -b & # old compton settings
sxhkd &
dropbox start &
~/bin/setfonts.sh
xsetroot -cursor_name left_ptr &
feh --bg-scale /home/zedexodus/Pictures/wallpapers/current-wallpaper &
trayer-srg --edge bottom --align right  --width 100% --height 18px --SetDockType true --expand true --transparent true --alpha 000 --tint 0x000000 &
xrandr --output DVI-D-0 --mode 1920x1080 --rate 120
exec systemd --user &
exec bspwm
