#! /bin/sh
bspc config border_width 1
bspc config window_gap 4
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
#bspc config bottom_padding 3
bspc config bottom_padding 15
bspc config top_padding 15
bspc monitor -d I II III IV V VI VII VIII IX X
bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
#bspc rule -a smplayer floating=on
bspc rule -a firefox floating=on
#bspc rule -a clementine floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop=^7 follow=off floating=on
bspc rule -a xfreerdp desktop=^6
# Start applications

panel &
